<?php

define('ODIN_ERROR_SYSTEM_ERROR_CODE', 63001);
define('ODIN_ERROR_SYSTEM_ERROR_STRING', '系统故障');

define('ODIN_ERROR_MISSING_PARAMETER_CODE', 63002);
define('ODIN_ERROR_MISSING_PARAMETER_STRING', '缺失参数');

define('ODIN_ERROR_WRONG_HASH_CODE', 63003);
define('ODIN_ERROR_WRONG_HASH_STRING', '接口令牌验证失败');

define('ODIN_ERROR_NO_TIME_LEFT_CODE', 63004);
define('ODIN_ERROR_NO_TIME_LEFT_STRING', '余额不足');

define('ODIN_ERROR_ACCOUNT_DISABLED_CODE', 63005);
define('ODIN_ERROR_ACCOUNT_DISABLED_STRING', '账号已被禁用');

define('ODIN_ERROR_NO_SUCH_INTERFACE_CODE', 63006);
define('ODIN_ERROR_NO_SUCH_INTERFACE_STRING', '接口不存在');

define('ODIN_ERROR_INTERFACE_DISABLED_CODE', 63007);
define('ODIN_ERROR_INTERFACE_DISABLED_STRING', '接口已停用');

define('ODIN_ERROR_NO_PERMISSION_CODE', 63008);
define('ODIN_ERROR_NO_PERMISSION_STRING', '权限不足');

define('ODIN_ERROR_NOT_FOUND_CODE', 404);
define('ODIN_ERROR_NOT_FOUND_STRING', '你好像发现了未知领域');